#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument.
#If it's just $#, it's the number of positional parameters, like $1, $2, $3. (Not counting $0, mind you.)
if [ "$#" -eq 0 ]; then
   echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
