#!/usr/bin/env bash
#sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default : same cp
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo systemctl stop nginx
