#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8
#The -i option comes in handy to edit the original file itself.
#If you use the -i option the sed command replaces the text in the original file itself
#rather than displaying it on the terminal.
#cp -f : Delete existing target files
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
